/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.print.DocFlavor;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.User;


/**
 *
 * @author User
 */
public class FormJPanel extends javax.swing.JPanel {
    private Image photo;
    private JPanel bottomPanel;
    
// Add this line with your other variable declarations
    private java.io.File selectedPhoto;
    /**
     * Creates new form FormJPanel
     */
    public FormJPanel() {
        initComponents();
    }
     /**
     * Creates new form JPanel with access to the panel passed as an argument 
     *@param panel
     */
    public FormJPanel(JPanel panel){
        initComponents();
        
    this.bottomPanel = panel;
    }       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderComboBox = new javax.swing.JComboBox<>();
        ageSpinner = new javax.swing.JSpinner();
        age = new javax.swing.JLabel();
        lastnameTextfield = new javax.swing.JTextField();
        firstname = new javax.swing.JLabel();
        continentComboBox = new javax.swing.JComboBox<>();
        phoneFormattedTextField = new javax.swing.JFormattedTextField();
        gender = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbiesTextArea = new javax.swing.JTextArea();
        emailTextField = new javax.swing.JTextField();
        phoneLabel1 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        firstnameTextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        photoButton = new javax.swing.JButton();
        RegistrationLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        photoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 255));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderComboBox.setSelectedIndex(-1);

        ageSpinner.setAutoscrolls(true);

        age.setText("Age:");

        lastnameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextfieldActionPerformed(evt);
            }
        });

        firstname.setText("First Name:");

        continentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Africa", "Antarctica", "Asia", "Europe", "North America", "South America", "Australia" }));
        continentComboBox.setSelectedIndex(-1);

        try {
            phoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneFormattedTextField.setToolTipText("123-456-7890");
        phoneFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFormattedTextFieldActionPerformed(evt);
            }
        });

        gender.setText("Gender:");

        hobbiesTextArea.setColumns(20);
        hobbiesTextArea.setRows(5);
        jScrollPane1.setViewportView(hobbiesTextArea);

        phoneLabel1.setText("Phone:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Email:");

        lastname.setText("Last Name:");

        jLabel3.setText("Hobbies:");

        jLabel2.setText("Continent:");

        photoButton.setText("Upload");
        photoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoButtonActionPerformed(evt);
            }
        });

        RegistrationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegistrationLabel.setText("Registration");

        photoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Photo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(RegistrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(firstnameTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                        .addComponent(lastnameTextfield)
                                        .addComponent(phoneFormattedTextField)
                                        .addComponent(emailTextField)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ageSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(genderComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 117, Short.MAX_VALUE))
                                        .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(lastname)
                                            .addComponent(gender)
                                            .addComponent(phoneLabel1)
                                            .addComponent(jLabel1)
                                            .addComponent(age))
                                        .addGap(284, 284, 284))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)))
                                .addComponent(firstname, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addComponent(photoButton)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(RegistrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname)
                    .addComponent(firstnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname)
                    .addComponent(lastnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel1)
                    .addComponent(phoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photoButton)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(submitButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextfieldActionPerformed

    private void phoneFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFormattedTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        // Read all input fields
        String firstName = firstnameTextfield.getText().trim();
        String lastName = lastnameTextfield.getText().trim();
        String gender = genderComboBox.getSelectedItem().toString();
        int age = (Integer) ageSpinner.getValue();
        String phone = phoneFormattedTextField.getText().trim();
        String email = emailTextField.getText().trim();
        String continent = continentComboBox.getSelectedItem().toString();
        String hobbies = hobbiesTextArea.getText().trim();

        // === Validation ===
        if (firstName.isEmpty() || lastName.isEmpty() || phone.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        
        }
        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Invalid email format!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // === Create User object with uploaded photo ===
        User user = new User(firstName, lastName, gender, age, phone, email, continent, hobbies, selectedPhoto);
/**
*Navigate to view page
*/

//create Object of type viewJPanel
ViewJPanel viewJPanelObject = new ViewJPanel(user);
this.bottomPanel.add(viewJPanelObject);

//navigate to the next page
CardLayout layout = (CardLayout)this.bottomPanel.getLayout();
layout.next(this.bottomPanel);
//get access to bottomJPanel
JPanel bottomPanel = new JPanel();
        
        // === Show success popup with user.toString() ===
        if (selectedPhoto != null) {
            ImageIcon icon = new ImageIcon(new ImageIcon(selectedPhoto.getAbsolutePath())
                .getImage().getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH));
            JOptionPane.showMessageDialog(this, user.toString(), "Profile", JOptionPane.INFORMATION_MESSAGE, icon);
        } else {
            JOptionPane.showMessageDialog(this, user.toString(), "Profile", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void photoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoButtonActionPerformed
JFileChooser fileChooser = new JFileChooser();
fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
    "Image files", "jpg", "jpeg", "png"
));

int result = fileChooser.showOpenDialog(this);

if (result == JFileChooser.APPROVE_OPTION) {
    File selectedPhoto = fileChooser.getSelectedFile();
    try {
        // Read the image
        BufferedImage img = ImageIO.read(selectedPhoto);

        // Resize the image smoothly to fit the label
        Image scaledImage = img.getScaledInstance(120, 140, Image.SCALE_SMOOTH);

        // Set the scaled image into the JLabel
        photoLabel.setIcon(new ImageIcon(scaledImage));

        // Display the image path in the JTextField
        photoTextField.setText(selectedPhoto.getAbsolutePath());

        // Optional success message
        JOptionPane.showMessageDialog(this, "Photo uploaded: " + selectedPhoto.getName());
        
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this,
            "Error loading image. Please try again.",
            "Image Upload Error",
            JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}

    }//GEN-LAST:event_photoButtonActionPerformed

    private void photoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoTextFieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_photoTextFieldActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegistrationLabel;
    private javax.swing.JLabel age;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JComboBox<String> continentComboBox;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstnameTextfield;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextArea hobbiesTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lastnameTextfield;
    private javax.swing.JFormattedTextField phoneFormattedTextField;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JButton photoButton;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField photoTextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
