/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;

/**
 *
 * @author mael
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        collegeButtonGroup = new javax.swing.ButtonGroup();
        registrationPanel = new javax.swing.JPanel();
        RegistrationLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        collegeLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        coeRadioButton = new javax.swing.JRadioButton();
        cosRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        LastnameLabel = new javax.swing.JLabel();
        lastnameTextField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        LastnameLabel1 = new javax.swing.JLabel();
        phonenumberTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrationPanel.setBackground(new java.awt.Color(102, 255, 255));

        RegistrationLabel.setText("Registration");

        firstnameLabel.setText("Firstname");

        ageLabel.setText("Age");

        collegeLabel.setText("College");

        collegeButtonGroup.add(coeRadioButton);
        coeRadioButton.setText("College of Engineering(COE)");
        coeRadioButton.setActionCommand("COE");

        collegeButtonGroup.add(cosRadioButton);
        cosRadioButton.setText("College of Science (COS)");
        cosRadioButton.setActionCommand("COS");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LastnameLabel.setText("Lastname");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });

        LastnameLabel1.setText("Gender");

        phoneNumberLabel.setText("Phone Number");

        emailLabel.setText("Email");

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstnameLabel)
                    .addComponent(ageLabel)
                    .addComponent(collegeLabel)
                    .addComponent(LastnameLabel)
                    .addComponent(LastnameLabel1)
                    .addComponent(phoneNumberLabel)
                    .addComponent(emailLabel))
                .addGap(51, 51, 51)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(ageTextField)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(coeRadioButton)
                    .addComponent(cosRadioButton)
                    .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phonenumberTextField)
                    .addComponent(emailTextField))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                        .addComponent(RegistrationLabel)
                        .addGap(279, 279, 279))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))))
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(RegistrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnameLabel)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnameLabel1)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(37, 37, 37)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phonenumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coeRadioButton)
                    .addComponent(collegeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cosRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(registrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Variable for error title
        String errorTitle = "Ooops";
        
        try {
            
            // Declare variables for ujser inputs
        String firstname;
        String lastname;
        String gender;
        int age;
        long phonenumber;
        String email;
        String college;
        
        // Extract and store user's data from components
        firstname = firstnameTextField.getText();

        
        // check name validity
        if (firstname.isBlank()){
                      
            JOptionPane.showMessageDialog(rootPane, "Invalid firstname provided", errorTitle, JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        
        lastname = lastnameTextField.getText();
        
         
             if (lastname.isBlank()){           
                 JOptionPane.showMessageDialog(rootPane, "Invalid lastname provided", errorTitle, JOptionPane.ERROR_MESSAGE);
                 return;
             }
        
        //extract and store user's age and college from components
        age = Integer.parseInt(ageTextField.getText());
        college = collegeButtonGroup.getSelection().getActionCommand();


        if (college.equals ("COE")){
            college = "College of Engineering (COE)";
        }
        
        if (college.equals ("COS")){
            college = "College of Science (COS)";
        }
 
        //check age validity
        if (age < 18){         
            JOptionPane.showMessageDialog(rootPane, "Invalid age provided", errorTitle, JOptionPane.ERROR_MESSAGE);
            return;
        }
            
         gender = genderComboBox.getSelectedItem().toString();
         if (gender.isBlank()){
                      
            JOptionPane.showMessageDialog(rootPane, "Invalid firstname provided", errorTitle, JOptionPane.ERROR_MESSAGE);
            return;
            
        }
         
          phonenumber = Long.parseLong(phonenumberTextField.getText());
            
        if (phonenumber < 10){ 
                      
            JOptionPane.showMessageDialog(rootPane, "Invalid firstname provided", errorTitle, JOptionPane.ERROR_MESSAGE);
            return;
            
        }
            
          email = emailTextField.getText();
           
         if (email.isBlank()){
                      
            JOptionPane.showMessageDialog(rootPane, "Invalid firstname provided", errorTitle, JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        // Create a variable for success message
        String successMessage = "Name: " + firstname
                +"\nAge: " + age
                +"\nCollege: " + college;
                
        
         
         
        JOptionPane.showMessageDialog(rootPane, "Success!", errorTitle, JOptionPane.INFORMATION_MESSAGE);
         
       
        
       
       
       
      
        
        System.out.print(firstname + " " + lastname + " " + gender + " " + age + " " + phonenumber + " " + email + " " + college);     
       
        }catch (NumberFormatException e){
             JOptionPane.showMessageDialog(rootPane, "Invalid age provided", errorTitle, JOptionPane.ERROR_MESSAGE);
               
        }catch (NullPointerException e){
             JOptionPane.showMessageDialog(rootPane, "Invalid college provided", errorTitle, JOptionPane.ERROR_MESSAGE);
          
             } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Something went wrong", errorTitle, JOptionPane.ERROR_MESSAGE);
          
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastnameLabel;
    private javax.swing.JLabel LastnameLabel1;
    private javax.swing.JLabel RegistrationLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JRadioButton coeRadioButton;
    private javax.swing.ButtonGroup collegeButtonGroup;
    private javax.swing.JLabel collegeLabel;
    private javax.swing.JRadioButton cosRadioButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phonenumberTextField;
    private javax.swing.JPanel registrationPanel;
    // End of variables declaration//GEN-END:variables
}
